name: snowrag
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - pip
  - pip:
      - pyarrow
      - snowflake-connector-python
      - snowflake-snowpark-python
      - snowflake-ml-python
      - langchain
      - langchain-core
      - langchain-community
      - langchain-unstructured
      - unstructured
      - unstructured-client
      - "unstructured[pdf]"
      - python-magic
      - docx2txt
      - beautifulsoup4
      - streamlit
      - cryptography
      - pydantic
      - fitz  # PyMuPDF
      - pymupdf
      - tqdm
      - pytest
      - requests
      - -r requirements.txt
