// Querying the `LANGCHAIN_PFLEGE` table
SELECT count(*) FROM LANGCHAIN_PFLEGE;

// Querying the `LANGCHAIN_PFLEGE` table
SELECT * FROM LANGCHAIN_PFLEGE;

// Querying the `LANGCHAIN_TEST` table
SELECT * FROM LANGCHAIN_TEST3;

// Dropping the `LANGCHAIN` table
DROP TABLE IF EXISTS LANGCHAIN_TEST3;

// Renaming the `LANGCHAIN_TEST` table to `LANGCHAIN_FUNKTIONSDIENSTE`
ALTER TABLE LANGCHAIN_TEST RENAME TO LANGCHAIN_FUNKTIONSDIENSTE;